# Generated by Django 3.2 on 2022-03-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='updates',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default='Klara Thunberg', max_length=200),
        ),
    ]
